/* Requires the Docker Pipeline plugin */
pipeline {
    agent { 
        docker { 
            image 'node:18.18.0-alpine3.18' 
        } 
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh '''
                    npm install
                    npm run build
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}